# Generated by Django 4.2.9 on 2026-06-09 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name="повне ім'я")),
                ('role', models.CharField(max_length=128, verbose_name='посада')),
                ('bio', models.TextField(blank=True, verbose_name='про себе')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='телефон')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='місто')),
                ('github', models.CharField(blank=True, max_length=255, verbose_name='github/сайт')),
                ('telegram', models.CharField(blank=True, max_length=128, verbose_name='telegram')),
                ('linkedin', models.CharField(blank=True, max_length=255, verbose_name='linkedin')),
                ('skills', models.JSONField(default=list, verbose_name='навички')),
                ('theme', models.CharField(choices=[('dark-neon', 'Dark Neon'), ('clean-light', 'Clean Light'), ('warm-cream', 'Warm Cream'), ('ocean-blue', 'Ocean Blue'), ('forest-green', 'Forest Green'), ('sunset-red', 'Sunset Red'), ('minimal-gray', 'Minimal Gray'), ('purple-haze', 'Purple Haze')], default='dark-neon', max_length=32, verbose_name='тема')),
                ('layout', models.CharField(choices=[('centered', 'Centered'), ('sidebar', 'Sidebar'), ('hero', 'Hero'), ('cards', 'Cards'), ('terminal', 'Terminal'), ('magazine', 'Magazine')], default='centered', max_length=32, verbose_name='макет')),
                ('sphere', models.CharField(default='developer', max_length=32, verbose_name='сфера')),
                ('generated_html', models.TextField(blank=True, verbose_name='згенерований HTML')),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True, verbose_name='slug')),
                ('is_public', models.BooleanField(default=True, verbose_name='публічна')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='перегляди')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'візитка',
                'verbose_name_plural': 'візитки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='назва')),
                ('description', models.TextField(blank=True, verbose_name='опис')),
                ('link_label', models.CharField(default='Переглянути', max_length=64, verbose_name='текст кнопки')),
                ('link_url', models.URLField(blank=True, verbose_name='URL посилання')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='фонове зображення')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cards.card')),
            ],
            options={
                'verbose_name': 'проєкт',
                'verbose_name_plural': 'проєкти',
                'ordering': ['order'],
            },
        ),
    ]
