# Generated by Codex on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="content_blocks",
            field=models.JSONField(blank=True, default=list, verbose_name="кастомні блоки"),
        ),
        migrations.AddField(
            model_name="card",
            name="design_settings",
            field=models.JSONField(blank=True, default=dict, verbose_name="налаштування дизайну"),
        ),
        migrations.AlterField(
            model_name="card",
            name="layout",
            field=models.CharField(
                choices=[
                    ("centered", "Centered"),
                    ("sidebar", "Sidebar"),
                    ("hero", "Hero"),
                    ("cards", "Cards"),
                    ("terminal", "Terminal"),
                    ("magazine", "Magazine"),
                    ("deck", "Presentation Deck"),
                    ("resume", "Resume"),
                    ("split-showcase", "Split Showcase"),
                    ("gallery", "Gallery"),
                    ("product", "Product"),
                ],
                default="centered",
                max_length=32,
                verbose_name="макет",
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="theme",
            field=models.CharField(
                choices=[
                    ("dark-neon", "Dark Neon"),
                    ("clean-light", "Clean Light"),
                    ("warm-cream", "Warm Cream"),
                    ("ocean-blue", "Ocean Blue"),
                    ("forest-green", "Forest Green"),
                    ("sunset-red", "Sunset Red"),
                    ("minimal-gray", "Minimal Gray"),
                    ("purple-haze", "Purple Haze"),
                    ("aurora", "Aurora"),
                    ("mono-lime", "Mono Lime"),
                    ("rose-gold", "Rose Gold"),
                    ("glass-blue", "Glass Blue"),
                    ("custom", "Custom"),
                ],
                default="dark-neon",
                max_length=32,
                verbose_name="тема",
            ),
        ),
    ]
